on:
  release:
    types: [published]

env:
  LINK_PYTORCH : | 
    https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.13.1%2Bcpu.zip

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "workspace: " ${{ github.workspace }} "version: " ${{ github.event.release.tag_name }}

      ##### ManyLinux 2014 server compilation #####
      - name: Docker run action
        uses: addnab/docker-run-action@v3
        with:
          image: quay.io/pypa/manylinux2014_x86_64
          options: -v ${{ github.workspace }}:/io
          run: |
            echo "Hello docker friend"

            cd io/

            # rustup installation
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh
            sh rustup.sh -y
            export PATH=$HOME/.cargo/bin:$PATH

            # libtorch installation
            yum -y install \
              zip openssl-devel \
              devtoolset-11-toolchain

            curl -o libtorch.zip ${{ env.LINK_PYTORCH }}
            unzip libtorch.zip

            export LIBTORCH=$PWD/libtorch
            export LD_LIBRARY_PATH=$LIBTORCH/lib:$LD_LIBRARY_PATH

            cd server/

            # Build server binary
            scl enable devtoolset-11 'LIBTORCH_PATH="$(dirname $(pwd))/libtorch" make all'

            # Compress server binary
            zip basionlab-${{ github.event.release.tag_name }}-linux.zip \
              bin/bastionlab \
              bin/config.toml \
              bin/data_frames/
            
      ##### Upload binary to release #####
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: server/bastionlab-${{ github.event.release.tag_name }}-linux.zip
