name: Iterate over all secrets
on: [push]
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Print all vars
        run: |
          for var_name in ${{ vars.* }}; do
            echo "Secret name: $var_name"
            echo "Secret value: ${{ fromJSON($vars)[$var_name] }}"
          done
