name: Verify Config Variable Change
on:
  push:
    branches:
      - main
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Verify config variable
        run: |
          for var in ${{ vars }}; do
            echo "Variable: $var"
            echo "Value: ${{ vars[var] }}"
          done