name: Verify Config Variable Change
on:
  push:
    branches:
      - main
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Verify config variable
        run: |
          for change in ${{ toJson(github.event.changes()) }}; do
            if [[ $change.key == "vars.LIBTORCH_VERSION" ]]; then
              echo "MY_VARIABLE has been modified"
              current_value=${{ vars.LIBTORCH_VERSION }}
              previous_value=$change.from
              if [[ "$current_value" != "$previous_value" ]]; then
                echo "Variable has changed"
              else
                echo "Variable has not changed"
              fi
              break
            fi
          done
