name: Iterate over all secrets
on: [push]
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Print all vars
        run: |
          for var_name in ${{ vars.* }}; do
            if [[ ! -z "${!var_name}" ]];then
              echo "Secret name: $var_name = ${!var_name}"
            fi
          done
