name: Verify Config Variable Change
on:
  push:
    branches:
      - main
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Verify config variable
        run: |
          for variable in ${{ vars }}; do
            echo "Variable: $variable"
            echo "Value: ${{ vars[variable] }}"
          done